### ISSUE TITLE
[DrawerVnext] Touch events not forwarded when view controller is embedded in content

### ISSUE THREAD

**Issue by kubalani** [microsoft/fluentui-apple#359]
### Environment Information

- **Platform**:
  - [X] iOS
  - [ ] macOS
- **Package version(s)**: (fill this out, include which package manager you're using)
- **Xcode and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug:

Bug replicates on iOS 13 only

- Open DrawerVnextController
- Expand Drawer by any side
- Tap on `Dismiss` button

#### Actual behavior:

Drawer is not dismissed

#### Expected behavior:

Drawer to be dismissed

### Priorities and help requested:

If vNext branch, doesn't affect master yet

**Comment by rdeassis** [comment]
Updating the issue with more info:

1. The problem is not exclusive to iOS13. I'm able to consistently reproduce it in iOS 14 as well.
2. This issue doesn't affect only the ButtonVnext. It it also impacting other SwiftUI controls.
3. The culprit of the issue lies on the following snippet in the [animateTransition method (Drawer+UIKit.swift file)](https://github.com/microsoft/fluentui-apple/blob/cf07ce76e60845b84cebbf174af0a24cd071ee1c/ios/FluentUI/DrawerVnext/Drawer%2BUIKit.swift#L25):

```
        // delegate animation to swiftui by changing state
        if isPresentingDrawer {
            transitionContext.containerView.addSubview(drawerView)
            drawerView.frame = UIScreen.main.bounds
            DispatchQueue.main.asyncAfter(deadline: .now() + state.animationDuration) { [weak self] in
                if let strongSelf = self {
                    strongSelf.state.isExpanded = isPresentingDrawer
                }
                transitionContext.completeTransition(true)
            }
        } else {
            self.state.isExpanded = isPresentingDrawer
            DispatchQueue.main.asyncAfter(deadline: .now() + state.animationDuration) {
                drawerView.removeFromSuperview()
                transitionContext.completeTransition(true)
            }
        }
```

Because the animation transition blocks the UI interaction while it's happening, we can't interact with the controls until **transitionContext.completeTransition(true)** is called.

The fact that t**ransitionContext.completeTransition(true)** is being called asynchronously, there is a timing issue where the SwiftUI Views are not "unlocked" for interaction (probably because the transitionContext call didn't happen before it is "unlocked").

The video below shows a modified demo of the Drawer (running in iOS14) where the List is also being used in its contents. This proves points 1 and 2 above:

https://user-images.githubusercontent.com/68076145/104513450-8a67fb80-55a4-11eb-8092-4dccf736cccb.mov

If the async call is removed and **transitionContext.completeTransition(true)** is called right away, the interaction problem does not repro anymore (although the dismiss animation does not behave as expected as well as the presentation animation in the first time):


https://user-images.githubusercontent.com/68076145/104514461-25150a00-55a6-11eb-9aee-2e39809110a3.mov

**Comment by rdeassis** [comment]
Another bug finding:

Presenting the drawer with no animation does not work:

To repro the issue, just change the animated parameter in the [DrawerVnextDemoController.swift](https://github.com/microsoft/fluentui-apple/blob/cf07ce76e60845b84cebbf174af0a24cd071ee1c/ios/FluentUI.Demo/FluentUI.Demo/Demos/DrawerVnextDemoController.swift#L122) in the presentation call:

present(drawerController, animated: **false**, completion: nil)
