### ISSUE TITLE
Build 2020 Feedback Thread - Fluent UI Apple

### ISSUE THREAD

**Issue by ejlayne** [microsoft/fluentui-apple#61]
Welcome Build 2020 participants! Did you get a chance to try out the Fluent UI Apple library
or watch our Build 2020 talk? If so, we want to hear your feedback! Let us know how we can make this even more useful to you moving forward.

Feel free to leave feedback on any of the following (and please keep feedback constructive and respectful):

- Likes
- Dislikes
- Bugs
- Areas for improvement

Thank you,
The Fluent UI Apple team

**Comment by vodolazkayamv** [comment]
Hi!
The framework is awesome! My team and I are currently using it to build a new neat-business-looking app and it works great, really saving us tons of time on UI.
The only issue we've bumped ourselves into is lack of theming. It looks like most of color-related properties are private for some reason. It's really confusing, as it only makes possible creating outlookish-blue apps which is certainly nice, but we'd love to bring some purple in 😄 Mainly for segmentedControl and badges.

Is there any workaround that we missed? Or may be is it a WIP and will be released as a feature soon enough?

Anyway, thanks for such a great job, demos are great and the components are really pleasure to use! We all here hope the project will live and evolve :)

**Comment by markavitale** [comment]
@vodolazkayamv glad to hear you're liking the framework! We're excited to hear that you are enjoying the framework and love hearing that the components are easy to use. 

Luckily it seems the framework should support your theming needs.

In [Colors.Swift](https://github.com/microsoft/fluentui-apple/blob/master/ios/FluentUI/Core/Colors.swift) the majority of the colors defined are public vars, but the most important are the primary colors. The primary colors are what give the "theme" color to the controls like the SegmentedControl and the BadgeView control. By default as you mentioned, the primary colors are based on the "communication blue" color theme.

You can test this out by visiting the "Colors" page on the test app and tapping "Change color"
![image](https://user-images.githubusercontent.com/658243/82839209-7c356580-9e83-11ea-9292-4884d5bb9c38.png)
It invokes this code, which swaps out the various primary colors (including tints and shades of that primary color)
```Swift
Colors.primary = UIColor(named: "Colors/DemoPrimaryColor") ?? Colors.communicationBlue
Colors.primaryTint10 = UIColor(named: "Colors/DemoPrimaryTint10Color") ?? Colors.Palette.communicationBlueTint10.color
Colors.primaryTint20 = UIColor(named: "Colors/DemoPrimaryTint20Color") ?? Colors.Palette.communicationBlueTint20.color
Colors.primaryTint30 = UIColor(named: "Colors/DemoPrimaryTint30Color") ?? Colors.Palette.communicationBlueTint30.color
Colors.primaryTint40 = UIColor(named: "Colors/DemoPrimaryTint40Color") ?? Colors.Palette.communicationBlueTint40.color
Colors.primaryShade10 = UIColor(named: "Colors/DemoPrimaryShade10Color") ?? Colors.Palette.communicationBlueShade10.color
Colors.primaryShade20 = UIColor(named: "Colors/DemoPrimaryShade20Color") ?? Colors.Palette.communicationBlueShade20.color
Colors.primaryShade30 = UIColor(named: "Colors/DemoPrimaryShade30Color") ?? Colors.Palette.communicationBlueShade30.color
```
You'll notice the "App specific color" section will change to the new colors provided by the test app:
![image](https://user-images.githubusercontent.com/658243/82839428-30cf8700-9e84-11ea-8844-ce3447085765.png)

After changing out the color theme for the app, you can visit the other pages and notice that they now respect the primary color theme:
| before | after|
|-------|--------|
|![image](https://user-images.githubusercontent.com/658243/82839473-53fa3680-9e84-11ea-967a-56576aa12673.png)| ![image](https://user-images.githubusercontent.com/658243/82839484-65dbd980-9e84-11ea-8a90-e32e7144bf4b.png) |
| ![image](https://user-images.githubusercontent.com/658243/82839517-8146e480-9e84-11ea-8820-3862530a0787.png)| ![image](https://user-images.githubusercontent.com/658243/82839498-768c4f80-9e84-11ea-8e42-f027402bdcf6.png) |

Please let me know if this level of color theming is what you are looking for or if there are other ways in which we could improve.

**Comment by vodolazkayamv** [comment]
Cool, thanks for pointing this out! It is really something I missed completely :D And that's exactly what we need! Super handy, love it! ❤️ 

I'm still confused about how to add an accent color to a component though. Setting `.backgroundColor` works great for buttons (but obviously doesn't override `highlighted` state color, which is troubling), but for badges for example it behaves awkwardly (see attached screen)

![image](https://user-images.githubusercontent.com/13648809/82893104-32b74a00-9f59-11ea-9a01-61c07d5c174f.png)
```swift
let badge = BadgeView(dataSource: BadgeViewDataSource(text: "La La land"))
badge.backgroundColor = Colors.Palette.red10.color
let badge2 = BadgeView(dataSource: BadgeViewDataSource(text: "Whiplash"))
```

I guess that's the base UIView of the badge that's being colored in red via `backgroundColor`. And it is accessible instead badge's `backgroundView` because you can't just fileprivate UIView's properties, i guess 🤔What if this accessor (`backgroundColor` setter) would be overriden for BadgeView to change `backgroundView.backgroundColor` color instead? Seems like an elegant way to make badges a bit more customizable. But as with buttons, it doesn't really do anything with selected color, so I guess we need to create extension for styles somehow?

My goal actually is to spawn specific-colored badges (and buttons!). I mean, I have certain quantity of predefined tags for and object and I want them to appear like colored badges (e.g. tag 'nice' is always pink, tag 'grumpy' is always brown, etc.). So when I'm spawning a badge I know which color it should be, and it's probably one of the accent colors of the app's palette. 

PS: I think having a theming page in a wiki with best practices would be helpful! 🙏

**Comment by markavitale** [comment]
@vodolazkayamv thanks for clarifying what you're looking to achieve. As of right now the `BadgeView` and `Button` components are customizable at a per-app level by setting custom primary colors, but they are not customizable at a per-instance level (BadgeView does have the three preset "default", "error", and "warning" styles but nothing beyond that).

The button background color, as you've noticed, is just the UIView background color property, nothing specific to this control, so by setting that it's just changing the color behind the button visuals itself. I'm not aware of any current plans to make the badge and button colors customizable at the instance level as opposed to globally via the primary colors, but if you log a feature request we can discuss adding that support and try to prioritize it alongside our other planned improvements. I suspect you're not alone in your interest in per-instance color customization of these controls.
 
Just as a heads up, there is some more work happening right now in #75 that does change the recommended pattern for customizing the colors at the window level for better boot performance. I agree that we should have some better documentation for the best practices of theming for this repository, so if you could log an issue tracking that as well, I'd really appreciate it!
 
Thanks,
Mark
